const $=id=>document.getElementById(id);
let decrypt=false;
const descriptions={
"Caesar Cipher":"Shifts letters by a fixed numerical key.",
"Monoalphabetic Cipher":"Maps each alphabet letter to a unique substitution.",
"Playfair Cipher":"Encrypts pairs of letters using a 5×5 key matrix.",
"Hill Cipher":"Uses matrix multiplication over modular arithmetic.",
"Vigenere Cipher":"Applies repeated key shifts to alphabetic characters.",
"One-Time Pad":"Uses a key stream to combine plaintext with equal-length key material.",
"Rail Fence Cipher":"Rearranges text through a zig-zag rail pattern.",
"Columnar Transposition Cipher":"Reorders characters according to a keyed column order."
};
Object.keys(descriptions).forEach((n,i)=>{let c=document.createElement('article');c.className='card';c.innerHTML=`<div class="num">0${i+1}</div><h3>${n}</h3><p>${descriptions[n]}</p>`;$('cards').appendChild(c)});

function caesar(s,k){k=((parseInt(k)||0)%26+26)%26;return s.replace(/[A-Za-z]/g,c=>{let b=c<='Z'?65:97;return String.fromCharCode((c.charCodeAt(0)-b+(decrypt?-k:k)+26)%26+b)})}
function vig(s,k){k=k.replace(/[^a-z]/gi,'').toUpperCase();if(!k)throw Error("Enter a Vigenere key.");let j=0;return s.replace(/[A-Za-z]/g,c=>{let sh=k.charCodeAt(j++%k.length)-65,b=c<='Z'?65:97;return String.fromCharCode((c.charCodeAt(0)-b+(decrypt?-sh:sh)+26)%26+b)})}
function mono(s,k){k=k.toUpperCase().replace(/[^A-Z]/g,'');if(k.length!==26)throw Error("Monoalphabetic key must contain 26 letters.");let a="ABCDEFGHIJKLMNOPQRSTUVWXYZ";if(new Set(k).size!==26)throw Error("Monoalphabetic key must use 26 unique letters.");return s.replace(/[A-Za-z]/g,c=>{let up=c.toUpperCase(),i=decrypt?k.indexOf(up):a.indexOf(up);return i<0?c:(decrypt?a[i]:k[i])===undefined?c:(c===up?(decrypt?a[i]:k[i]):(decrypt?a[i]:k[i]).toLowerCase())})}
function rail(s,r){r=parseInt(r);if(!r||r<2)throw Error("Rails must be at least 2.");if(!decrypt){let a=Array.from({length:r},()=>[]),row=0,dir=1;s.split('').forEach(ch=>{a[row].push(ch);if(row===0)dir=1;if(row===r-1)dir=-1;row+=dir});return a.flat().join('')}let pattern=[];let row=0,dir=1;for(let i=0;i<s.length;i++){pattern.push(row);if(row===0)dir=1;if(row===r-1)dir=-1;row+=dir}let counts=Array(r).fill(0);pattern.forEach(x=>counts[x]++);let rails=[],p=0;for(let n of counts){rails.push(s.slice(p,p+n).split(''));p+=n}return pattern.map(x=>rails[x].shift()).join('')}
function columnar(s,key){key=String(key).toUpperCase().replace(/[^A-Z]/g,'');if(!key)throw Error("Enter a word key.");let order=[...key].map((c,i)=>[c,i]).sort((a,b)=>a[0].localeCompare(b[0])||a[1]-b[1]).map(x=>x[1]);if(!decrypt){let out='';for(let col of order)for(let i=col;i<s.length;i+=key.length)out+=s[i];return out}let n=s.length,rows=Math.ceil(n/key.length),extra=n%key.length||key.length,cols=Array(key.length).fill(Math.floor(n/key.length));for(let i=0;i<extra;i++)cols[i]++;let arr=Array.from({length:rows},()=>Array(key.length).fill(''));let p=0;for(let col of order){for(let r=0;r<cols[col];r++)arr[r][col]=s[p++]}return arr.flat().join('')}
function playfair(text,key){key=key.toUpperCase().replace(/J/g,'I').replace(/[^A-Z]/g,'');let seq='';for(let c of key+'ABCDEFGHIKLMNOPQRSTUVWXYZ')if(!seq.includes(c))seq+=c;let pos=c=>[Math.floor(seq.indexOf(c)/5),seq.indexOf(c)%5];let pairs=[];text=text.toUpperCase().replace(/J/g,'I').replace(/[^A-Z]/g,'');if(decrypt){for(let i=0;i<text.length;i+=2)pairs.push(text.slice(i,i+2))}else{for(let i=0;i<text.length;i+=2){let a=text[i],b=text[i+1]||'X';if(a===b){b='X';i--}pairs.push(a+b)}}return pairs.map(pair=>{let [a,b]=pair;let [r1,c1]=pos(a),[r2,c2]=pos(b);if(r1===r2)return seq[r1*5+(c1+(decrypt?-1:1)+5)%5]+seq[r2*5+(c2+(decrypt?-1:1)+5)%5];if(c1===c2)return seq[((r1+(decrypt?-1:1)+5)%5)*5+c1]+seq[((r2+(decrypt?-1:1)+5)%5)*5+c2];return seq[r1*5+c2]+seq[r2*5+c1]}).join('')}
function run(){try{let c=$('cipher').value,s=$('input').value,k=$('key').value;if(!s)return $('status').textContent="Enter input first.";let out;switch(c){case"Caesar Cipher":out=caesar(s,k);break;case"Vigenere Cipher":out=vig(s,k);break;case"Monoalphabetic Cipher":out=mono(s,k);break;case"Rail Fence Cipher":out=rail(s,k);break;case"Columnar Transposition Cipher":out=columnar(s,k);break;case"Playfair Cipher":out=playfair(s,k);break;case"One-Time Pad":out=otp(s,k);break;case"Hill Cipher":out=hill(s,k);break}$('output').value=out;$('status').textContent="Completed successfully."}catch(e){$('status').textContent=e.message}}
function otp(s,k){k=k.replace(/[^A-Za-z]/g,'');let j=0;return s.replace(/[A-Za-z]/g,c=>{if(j>=k.length)throw Error("OTP key must be at least as long as the text.");let sh=k[j++].toUpperCase().charCodeAt(0)-65,b=c<='Z'?65:97;return String.fromCharCode((c.charCodeAt(0)-b+(decrypt?-sh:sh)+26)%26+b)})}
function hill(s,k){let nums=k.split(/[ ,]+/).map(Number).filter(Number.isFinite);if(nums.length!==4)throw Error("Hill key must be four numbers, e.g. 3 3 2 5.");let a=nums.map(x=>((x%26)+26)%26),det=(a[0]*a[3]-a[1]*a[2]+26)%26;let inv=Array.from({length:26},(_,i)=>i).find(x=>det*x%26===1);if(decrypt){if(inv===undefined)throw Error("Hill key matrix is not invertible modulo 26.");a=[a[3]*inv,-a[1]*inv,-a[2]*inv,a[0]*inv]}s=s.toUpperCase().replace(/[^A-Z]/g,'');if(s.length%2)s+='X';let out='';for(let i=0;i<s.length;i+=2){let x=s.charCodeAt(i)-65,y=s.charCodeAt(i+1)-65;out+=String.fromCharCode(((a[0]*x+a[1]*y)%26+26)%26+65);out+=String.fromCharCode(((a[2]*x+a[3]*y)%26+26)%26+65)}return out}
$('enc').onclick=()=>{decrypt=false;$('enc').classList.add('active');$('dec').classList.remove('active')};
$('dec').onclick=()=>{decrypt=true;$('dec').classList.add('active');$('enc').classList.remove('active')};
$('run').onclick=run;
$('clear').onclick=()=>{$('input').value='';$('output').value='';$('status').textContent=''};
$('copy').onclick=()=>navigator.clipboard.writeText($('output').value);
$('sample').onclick=()=>{$('input').value= $('cipher').value==="Caesar Cipher"?"NETWORK SECURITY":"HELLO WORLD"};
$('random').onclick=()=>{let c=$('cipher').value;if(c==="Caesar Cipher")$('key').value=Math.floor(Math.random()*25)+1;else if(c==="Rail Fence Cipher")$('key').value=Math.floor(Math.random()*4)+2;else if(c==="Vigenere Cipher")$('key').value=Math.random().toString(36).slice(2,7).toUpperCase();else $('key').value="KEY"};
$('cipher').onchange=()=>{let c=$('cipher').value;$('hint').textContent={ "Caesar Cipher":"Caesar key: enter a number such as 5.","Monoalphabetic Cipher":"Use 26 unique letters as the substitution alphabet.","Playfair Cipher":"Enter a word to build the 5×5 key square.","Hill Cipher":"Enter four numbers for a 2×2 matrix, e.g. 3 3 2 5.","Vigenere Cipher":"Enter a word or phrase as the repeating key.","One-Time Pad":"Use alphabetic key material at least as long as the message.","Rail Fence Cipher":"Enter the number of rails, e.g. 3.","Columnar Transposition Cipher":"Enter a word key; repeated letters are handled left-to-right."}[c]||""};
